### ISSUE TITLE
Request contains an invalid argument 'read_mask', says 'Field is required'

### ISSUE THREAD

**Issue by awalker88** [google/alligator2#12]
Hey all, I think this repo is a really cool and I'd like to try it out, but I get this error when I run `main.py` that says I have an invalid argument and that "read_mask" is required. Seems like it's triggered when it tries to pull locations for my account.

```
Traceback (most recent call last):
  File "C:\Users\awalker1\AppData\Local\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\awalker1\AppData\Local\JetBrains\PyCharm 2021.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/awalker1/Projects/alligator2-master/main.py", line 238, in <module>
    main(sys.argv[1:])
  File "C:/Users/awalker1/Projects/alligator2-master/main.py", line 230, in main
    Alligator.for_account(project_id, account_id, language, flags)
  File "C:/Users/awalker1/Projects/alligator2-master/main.py", line 59, in for_account
    locations = api.locations(u"accounts/{}".format(account_id))
  File "C:\Users\awalker1\Projects\alligator2-master\api.py", line 135, in locations
    response_json = self.gmb_service.accounts().locations().list(
  File "C:\Users\awalker1\Projects\venv\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\awalker1\Projects\venv\lib\site-packages\googleapiclient\http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://mybusinessbusinessinformation.googleapis.com/v1/accounts/redacted_account_number/locations?alt=json returned "Request contains an invalid argument.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'read_mask', 'description': 'Field is required'}]}]">
```

Maybe it's caused by a discovery docs changing? Let me know if more info is needed.

**Comment by awalker88** [comment]
My bad, looks like the issue was that I mixed up the contents of `gmb_discovery.json` and `mybusinessaccountmanagement_discovery.json`. Working great now!

**Comment by tonycoco** [comment]
Thanks!
